name: wazzaf
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.6
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_storage: ^10.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_conditional_rendering: ^2.0.0
  flutter_dropdown: ^1.0.0+hotfix.1
  flutter_polyline_points: ^1.0.0
  fluttertoast: ^8.0.8
  geolocator: ^8.0.3
  google_maps_flutter: ^2.1.1
  hexcolor: ^2.0.6
  image_picker: ^0.8.4+5
  reorderableitemsview: ^2.0.1
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
