name: wazzaf
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  cached_network_image: ^3.2.0
  chewie: ^1.3.0
  cloud_firestore: ^3.1.6
  cupertino_icons: ^1.0.2
  day_night_switcher: ^0.2.0+1
  fijkplayer: ^0.10.1
  file_picker: ^4.4.0
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_core_platform_interface: ^4.2.4
  firebase_messaging: ^11.2.8
  firebase_storage: ^10.2.5
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.3.0
  flutter_bloc: ^8.0.1
  flutter_conditional_rendering: ^2.0.0
  flutter_dropdown: ^1.0.0+hotfix.1
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.3.3
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.0
  fluttertoast: ^8.0.8
  geolocator: ^8.0.3
  google_maps_flutter: ^2.1.1
  hexcolor: ^2.0.6
  image_picker: ^0.8.4+5
  intl_phone_field: ^3.0.1
  page_transition: ^2.0.5
  path_provider: ^2.0.9
  permission_handler: ^9.1.0
  random_string: ^2.3.1
  reorderableitemsview: ^2.0.1
  shared_preferences: ^2.0.12
  splash_screen_view: ^3.0.0
  stacked: ^2.2.8
  video_player: ^2.2.18
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/wazzaf.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
